QT.widgetioc.VERSION = 5.15.0
QT.widgetioc.name = McWidgetIoc
QT.widgetioc.module = McWidgetIoc
QT.widgetioc.libs = $$QT_MODULE_LIB_BASE
QT.widgetioc.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/McWidgetIoc
QT.widgetioc.bins = $$QT_MODULE_BIN_BASE
QT.widgetioc.libexecs = $$QT_MODULE_LIBEXEC_BASE
QT.widgetioc.imports = $$QT_MODULE_IMPORT_BASE
QT.widgetioc.depends = ioc
QT.widgetioc.DEFINES = MC_WIDGETIOC_LIB
QT_MODULES += widgetioc
