QT.mclogqt.VERSION = 5.15.0
QT.mclogqt.name = McLogQt
QT.mclogqt.module = McLogQt
QT.mclogqt.libs = $$QT_MODULE_LIB_BASE
QT.mclogqt.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/McLogQt
QT.mclogqt.bins = $$QT_MODULE_BIN_BASE
QT.mclogqt.libexecs = $$QT_MODULE_LIBEXEC_BASE
QT.mclogqt.imports = $$QT_MODULE_IMPORT_BASE
QT.mclogqt.depends = mcioc
QT.mclogqt.DEFINES = MC_LOGQT_LIB
QT_MODULES += mclogqt
