QT.logqt.VERSION = 5.15.0
QT.logqt.name = McLogQt
QT.logqt.module = McLogQt
QT.logqt.libs = $$QT_MODULE_LIB_BASE
QT.logqt.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/McLogQt
QT.logqt.bins = $$QT_MODULE_BIN_BASE
QT.logqt.libexecs = $$QT_MODULE_LIBEXEC_BASE
QT.logqt.imports = $$QT_MODULE_IMPORT_BASE
QT.logqt.depends = mcioc concurrent
QT.logqt.DEFINES = MC_LOGQT_LIB
QT_MODULES += logqt
