CONFIG += c++17

# 去掉IOC容器的依赖部分
#DEFINES += MC_NO_IOC

CONFIG(release, debug|release) {
    DEFINES += QT_MESSAGELOGCONTEXT
}

msvc {
    QMAKE_CFLAGS += /utf-8
    QMAKE_CXXFLAGS += /utf-8
}

QMAKE_CXXFLAGS_RELEASE = $$QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO
QMAKE_LFLAGS_RELEASE = $$QMAKE_LFLAGS_RELEASE_WITH_DEBUGINFO
